pipeline{
    agent{
        label 'DevServer'
    }
    tools {
        maven 'mymaven'
    }
    stages{
        stage('Build')
        {
            steps{
                echo "Maven has run"//sh 'mvn clean package'
            }
            post{
                success{
                    echo "artifacts has been generated" //archiveArtifacts artifacts: '**/target/*.jar'
                }
            }
        }
        stage('Test')
        {
            parallel
            {
                stage('stage A')
                {
                    steps
                    {
                        echo "This is A running parallely with B"
                    }                    
                }
                stage('stage B')
                {
                    steps
                    {
                        echo "This is A running parallely with B"
                    }                    
                }
            }
        }
        stage('Deploy')
        {
            steps
            {
                echo "This is Deploy stage"
            }
        }        
    } 
}