pipeline{
    agent{
        label 'DevServer'
    }
    tools {
        maven 'mymaven'
    }
    stages{
        stage('Build')
        {
            steps{
                sh 'mvn clean package'
            }
            post{
                success{
                    archiveArtifacts artifacts: '**/target/*.war'
                }
            }
        }
        stage('Test')
        {
            steps{
                echo "This is Test stage"
            }
        }
        stage('Deploy')
        {
            steps{
                echo "This is Deploy stage"
            }
        }        
    } 
}